version: '3'
services:
  app:
    container_name: NUXT
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile
    image: autoscriber-nuxt-image
    ports:
      - '3000:3000'
    volumes:
      - ..:/app
      - /app/node_modules